# Generated by Django 3.0.6 on 2020-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actorrole',
            fields=[
                ('id_act_role', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'actorrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_mobile', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id_hall', models.AutoField(primary_key=True, serialize=False)),
                ('hall_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'hall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id_repertoire', models.AutoField(primary_key=True, serialize=False)),
                ('performance_name', models.CharField(max_length=100)),
                ('length', models.TimeField()),
                ('description', models.TextField()),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'repertoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('role_description', models.TextField()),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id_seance', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'seance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id_staff', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('birthday', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id_theater', models.AutoField(primary_key=True, serialize=False)),
                ('theater_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'theater',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.IntegerField(unique=True)),
                ('isreserved', models.CharField(db_column='isReserved', max_length=1)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
